# Generated by Django 3.1.7 on 2021-03-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveStuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1)),
                ('categories', models.ManyToManyField(to='GiveStuff.Category')),
            ],
        ),
    ]
